"use client";

import { useCallback, useEffect, useState } from "react";

type ActivityType = "content" | "keywords" | "mindmap" | "multiple_choice" | "true_false" | "short_answer" | "ordering" | "matching";
type Slide = { id: string; type: ActivityType; title: string; content: string; items?: string[]; answer?: string; deliveryMode?: "classroom" | "home" };
type Deck = { id?: string; title: string; subject: string; grade: string; className: string; summary: string; durationMinutes: number; deliveryMode: "classroom"; status: "draft" | "published"; coverColor: string; objectives: string[]; sections: Slide[]; updatedAt?: string };

const labels: Record<ActivityType, { icon: string; label: string }> = {
  content: { icon: "▤", label: "Nội dung giảng dạy" }, keywords: { icon: "◆", label: "Từ khóa cần nhớ" }, mindmap: { icon: "⌘", label: "Sơ đồ tư duy" },
  multiple_choice: { icon: "A", label: "Nhiều lựa chọn" }, true_false: { icon: "✓", label: "Đúng/Sai 4 ý" }, short_answer: { icon: "…", label: "Trả lời ngắn" }, ordering: { icon: "↕", label: "Sắp xếp câu" }, matching: { icon: "⇄", label: "Nối câu" },
};
const id = () => `slide-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
const blank = (): Deck => ({ title: "", subject: "Ngữ văn", grade: "10", className: "10A1", summary: "", durationMinutes: 45, deliveryMode: "classroom", status: "draft", coverColor: "#6d4aff", objectives: [""], sections: [] });

async function request<T>(url: string, options?: RequestInit) {
  const response = await fetch(url, options); const result = await response.json() as T & { error?: string };
  if (!response.ok) throw new Error(result.error || "Không thể xử lý bài trình chiếu"); return result;
}

type GammaJob = { title: string; status: "pending" | "completed" | "failed"; gammaUrl?: string; exportUrl?: string; detail?: string };

export function ClassroomPresentationStudio({ notify }: { notify: (message: string) => void }) {
  const [decks, setDecks] = useState<Deck[]>([]); const [editing, setEditing] = useState<Deck | null>(null); const [presenting, setPresenting] = useState<Deck | null>(null); const [loading, setLoading] = useState(true);
  const [gamma, setGamma] = useState<GammaJob | null>(null);
  const exportToGamma = async (deck: Deck) => {
    setGamma({ title: deck.title, status: "pending", detail: "Đang gửi nội dung sang Gamma..." });
    try {
      const lesson = {
        title: deck.title, subject: deck.subject, grade: deck.grade, summary: deck.summary, objectives: deck.objectives,
        sections: deck.sections.map((slide) => slide.type === "multiple_choice"
          ? { title: slide.title, content: slide.content, type: "quiz", options: slide.items || [], correctAnswer: slide.answer || "" }
          : { title: slide.title, content: `${slide.content}${slide.items?.length ? `\n${slide.items.map((item) => `• ${item}`).join("\n")}` : ""}` }),
      };
      const response = await request<{ generationId: string }>("/api/presentations/gamma", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "generate", lesson }) });
      for (let attempt = 0; attempt < 36; attempt += 1) {
        await new Promise((resolve) => setTimeout(resolve, 5000));
        const status = await request<{ status?: string; gammaUrl?: string; exportUrl?: string }>("/api/presentations/gamma", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "status", generationId: response.generationId }) });
        if (status.status === "completed") { setGamma({ title: deck.title, status: "completed", gammaUrl: status.gammaUrl, exportUrl: status.exportUrl }); notify("Gamma đã tạo xong bài trình chiếu"); return; }
        if (status.status === "failed") throw new Error("Gamma báo lỗi khi tạo trình chiếu. Vui lòng thử lại.");
        setGamma({ title: deck.title, status: "pending", detail: `Gamma đang thiết kế slide... (${(attempt + 1) * 5}s)` });
      }
      throw new Error("Gamma xử lý quá lâu. Kiểm tra lại trong tài khoản Gamma của trung tâm.");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Không thể kết nối Gamma";
      setGamma({ title: deck.title, status: "failed", detail: message });
      notify(message);
    }
  };
  const load = useCallback(async () => { try { const result = await request<{ lessons: Deck[] }>("/api/elearning"); setDecks((result.lessons || []).map((item) => ({ ...item, deliveryMode: item.deliveryMode || item.sections?.[0]?.deliveryMode || "home" } as Deck)).filter((item) => item.deliveryMode === "classroom")); } catch (error) { notify(error instanceof Error ? error.message : "Không thể tải bài trình chiếu"); } finally { setLoading(false); } }, [notify]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  if (presenting) return <WebDeck deck={presenting} onExit={() => setPresenting(null)} />;
  if (editing) return <ClassroomBuilder deck={editing} onChange={setEditing} onExit={() => setEditing(null)} onPresent={() => setPresenting(editing)} onSaved={() => { setEditing(null); void load(); }} notify={notify} />;
  return <section className="classroom-studio">
    <div className="classroom-hero"><div><small>BÀI GIẢNG TRÌNH CHIẾU TRÊN LỚP</small><h2>Biến học liệu thành bài dạy web tương tác</h2><p>Tải slide, nội dung SGK và câu hỏi sẵn có. AI tổ chức thành nội dung giảng dạy, từ khóa, sơ đồ tư duy và hoạt động luyện tập để giáo viên điều khiển trực tiếp.</p><button onClick={() => setEditing(blank())}>＋ Tạo bài trình chiếu</button></div><div className="classroom-flow"><span><b>1</b>Tải học liệu</span><i>→</i><span><b>2</b>AI thiết kế</span><i>→</i><span><b>3</b>Dạy trên web</span></div></div>
    <div className="classroom-capabilities">{Object.entries(labels).map(([key, meta]) => <article key={key}><span>{meta.icon}</span><b>{meta.label}</b></article>)}</div>
    <div className="learning-section-head"><div><b>Kho bài giảng trên lớp</b><small>Tách riêng hoàn toàn với bài eLearning tự học ở nhà</small></div><button onClick={() => setEditing(blank())}>＋ Bài giảng mới</button></div>
    {gamma && <div className={`gamma-status ${gamma.status}`}><span>{gamma.status === "completed" ? "✓" : gamma.status === "failed" ? "!" : "◌"}</span><div><b>Xuất Gamma · {gamma.title}</b><small>{gamma.status === "completed" ? "Hoàn tất. Mở liên kết bên cạnh để xem hoặc tải PPTX." : gamma.detail}</small></div>{gamma.gammaUrl && <a href={gamma.gammaUrl} target="_blank" rel="noreferrer">Mở Gamma</a>}{gamma.exportUrl && <a href={gamma.exportUrl} target="_blank" rel="noreferrer">Tải PPTX</a>}<button onClick={() => setGamma(null)} aria-label="Đóng">×</button></div>}
    {loading ? <div className="learning-empty">Đang tải bài trình chiếu...</div> : decks.length === 0 ? <div className="learning-empty"><span>▣</span><b>Chưa có bài giảng trên lớp</b><p>Tải học liệu để AI tạo bài trình chiếu web đầu tiên.</p></div> : <div className="classroom-deck-grid">{decks.map((deck) => <article key={deck.id}><div><small>{deck.subject} · Lớp {deck.grade}</small><b>{deck.sections.length}</b><span>trang web</span></div><section><i>{deck.status === "published" ? "Sẵn sàng dạy" : "Bản nháp"}</i><h3>{deck.title}</h3><p>{deck.summary}</p><footer><button onClick={() => setEditing(deck)}>Chỉnh sửa</button><button className="present" onClick={() => setPresenting(deck)}>▶ Trình chiếu</button><button onClick={() => void exportToGamma(deck)} disabled={gamma?.status === "pending"}>⇪ Xuất Gamma</button></footer></section></article>)}</div>}
  </section>;
}

function ClassroomBuilder({ deck, onChange, onExit, onPresent, onSaved, notify }: { deck: Deck; onChange: (deck: Deck) => void; onExit: () => void; onPresent: () => void; onSaved: () => void; notify: (m: string) => void }) {
  const [step, setStep] = useState(deck.sections.length ? 3 : 1); const [files, setFiles] = useState<{ slides?: File; textbook?: File; exercises?: File }>({}); const [busy, setBusy] = useState(false); const [active, setActive] = useState(0);
  const set = (changes: Partial<Deck>) => onChange({ ...deck, ...changes });
  const generate = async () => { if (!deck.title.trim()) return notify("Vui lòng nhập tên bài học"); if (!files.slides && !files.textbook) return notify("Hãy tải slide hoặc nội dung sách giáo khoa"); setBusy(true); try { const result = await request<{ sections: Slide[] }>("/api/classroom-ai", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: deck.title, subject: deck.subject, grade: deck.grade, summary: deck.summary, objectives: deck.objectives, sources: Object.entries(files).filter(([, f]) => f).map(([type, f]) => ({ type, name: f?.name })) }) }); set({ sections: result.sections }); setStep(3); notify("AI đã tạo bài trình chiếu web. Thầy cô hãy duyệt và chỉnh sửa trước khi dạy."); } catch (error) { notify(error instanceof Error ? error.message : "Không thể tạo bài trình chiếu"); } finally { setBusy(false); } };
  const save = async (publish = false) => { if (!deck.title.trim() || !deck.sections.length) return notify("Bài giảng cần có tên và ít nhất một trang"); setBusy(true); try { const saved = await request<{ lesson: Deck }>("/api/elearning", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "save", id: deck.id, lesson: { ...deck, status: "draft", sections: deck.sections.map((s) => ({ ...s, deliveryMode: "classroom" })) } }) }); if (publish && saved.lesson.id) await request("/api/elearning", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "publish", id: saved.lesson.id }) }); notify(publish ? "Đã lưu và sẵn sàng trình chiếu trên lớp" : "Đã lưu bản nháp bài trình chiếu"); onSaved(); } catch (error) { notify(error instanceof Error ? error.message : "Không thể lưu bài trình chiếu"); } finally { setBusy(false); } };
  const updateSlide = (changes: Partial<Slide>) => set({ sections: deck.sections.map((s, i) => i === active ? { ...s, ...changes } : s) });
  const add = (type: ActivityType) => { const next = [...deck.sections, { id: id(), type, title: labels[type].label, content: "", items: type === "true_false" ? ["Ý a", "Ý b", "Ý c", "Ý d"] : [] }]; set({ sections: next }); setActive(next.length - 1); };
  return <section className="classroom-builder"><header><button onClick={onExit}>← Kho bài giảng</button><div><b>{deck.id ? "Chỉnh sửa bài trình chiếu" : "Tạo bài trình chiếu trên lớp"}</b><small>Quy trình riêng cho dạy học trực tiếp</small></div><nav><button onClick={onPresent} disabled={!deck.sections.length}>▷ Xem thử</button><button onClick={() => void save(false)} disabled={busy}>Lưu nháp</button><button className="publish" onClick={() => void save(true)} disabled={busy}>Sẵn sàng dạy</button></nav></header>
    <div className="builder-steps"><button className={step === 1 ? "active" : ""} onClick={() => setStep(1)}><b>1</b><span>Nội dung bài học<small>Thông tin và học liệu nguồn</small></span></button><button className={step === 2 ? "active" : ""} onClick={() => setStep(2)}><b>2</b><span>AI thiết kế<small>Cấu trúc trang và hoạt động</small></span></button><button className={step === 3 ? "active" : ""} onClick={() => setStep(3)} disabled={!deck.sections.length}><b>3</b><span>Biên tập & trình chiếu<small>Duyệt trước khi lên lớp</small></span></button></div>
    {step === 1 && <main className="source-builder"><section><h3>Thông tin bài dạy</h3><div className="source-fields"><label className="wide">Tên bài học<input value={deck.title} onChange={(e) => set({ title: e.target.value })} placeholder="Ví dụ: Chuyển động cơ học" /></label><label>Môn học<input value={deck.subject} onChange={(e) => set({ subject: e.target.value })} /></label><label>Khối<select value={deck.grade} onChange={(e) => set({ grade: e.target.value })}><option>10</option><option>11</option><option>12</option></select></label><label className="wide">Nội dung trọng tâm<textarea value={deck.summary} onChange={(e) => set({ summary: e.target.value })} placeholder="Mô tả chủ đề, phạm vi kiến thức và yêu cầu cần đạt..." /></label><label className="wide">Mục tiêu bài học<textarea value={deck.objectives.join("\n")} onChange={(e) => set({ objectives: e.target.value.split("\n") })} placeholder="Mỗi mục tiêu trên một dòng" /></label></div></section><section><h3>Học liệu để AI xây dựng bài giảng</h3><div className="classroom-uploads"><UploadCard icon="P" title="Slide trình chiếu có sẵn" note="PPT, PPTX hoặc PDF" file={files.slides} accept=".ppt,.pptx,.pdf" onFile={(slides) => setFiles({ ...files, slides })} /><UploadCard icon="S" title="Nội dung sách giáo khoa" note="Word, PDF hoặc PowerPoint" file={files.textbook} accept=".doc,.docx,.pdf,.ppt,.pptx" onFile={(textbook) => setFiles({ ...files, textbook })} /><UploadCard icon="?" title="Câu hỏi luyện tập có sẵn" note="Word, Excel, PDF" file={files.exercises} accept=".doc,.docx,.xls,.xlsx,.pdf" onFile={(exercises) => setFiles({ ...files, exercises })} /></div><button className="next-builder" onClick={() => setStep(2)}>Tiếp tục cấu hình AI →</button></section></main>}
    {step === 2 && <main className="ai-classroom-config"><div><small>AI CLASSROOM DESIGNER</small><h2>Tạo bài dạy phù hợp màn chiếu và nhịp học trên lớp</h2><p>AI sẽ đọc nội dung đã cung cấp, tổ chức mỗi trang tập trung một ý, tạo từ khóa, sơ đồ tư duy và hoạt động kiểm tra nhanh.</p></div><section><h3>Cấu trúc sẽ tạo</h3><div>{Object.entries(labels).map(([type, meta]) => <label key={type}><input type="checkbox" defaultChecked /><span>{meta.icon}</span><b>{meta.label}</b></label>)}</div><label className="teacher-note">Yêu cầu thêm cho AI<textarea placeholder="Ví dụ: ưu tiên hình ảnh trực quan, có hoạt động nhóm 5 phút, câu hỏi bám sát bài 3 SGK..." /></label><button onClick={() => void generate()} disabled={busy}>{busy ? "AI đang phân tích học liệu..." : "✦ Tạo bài trình chiếu web"}</button></section></main>}
    {step === 3 && <main className="web-slide-editor"><aside><div><b>Cấu trúc bài giảng</b><small>{deck.sections.length} trang</small></div><nav>{deck.sections.map((slide, index) => <button key={slide.id} className={index === active ? "active" : ""} onClick={() => setActive(index)}><span>{index + 1}</span><div><b>{slide.title}</b><small>{labels[slide.type]?.label || slide.type}</small></div></button>)}</nav><section><b>Thêm trang / hoạt động</b>{Object.entries(labels).map(([type, meta]) => <button key={type} onClick={() => add(type as ActivityType)}><span>{meta.icon}</span>{meta.label}</button>)}</section></aside>{deck.sections[active] && <section className="slide-form"><header><span>{labels[deck.sections[active].type]?.icon}</span><div><small>TRANG {active + 1}</small><b>{labels[deck.sections[active].type]?.label}</b></div><button onClick={() => { const next = deck.sections.filter((_, i) => i !== active); set({ sections: next }); setActive(Math.max(0, active - 1)); }}>Xóa</button></header><label>Tiêu đề trang<input value={deck.sections[active].title} onChange={(e) => updateSlide({ title: e.target.value })} /></label><label>Nội dung giảng dạy<textarea rows={8} value={deck.sections[active].content} onChange={(e) => updateSlide({ content: e.target.value })} /></label><label>{deck.sections[active].type === "matching" ? "Các cặp nối (vế trái::vế phải)" : deck.sections[active].type === "true_false" ? "Bốn ý đúng/sai (mỗi ý một dòng)" : "Các ý / phương án (mỗi ý một dòng)"}<textarea rows={6} value={(deck.sections[active].items || []).join("\n")} onChange={(e) => updateSlide({ items: e.target.value.split("\n").filter(Boolean) })} /></label>{!new Set(["content", "keywords", "mindmap"]).has(deck.sections[active].type) && <label>Đáp án đúng<input value={deck.sections[active].answer || ""} onChange={(e) => updateSlide({ answer: e.target.value })} placeholder="Nhập đáp án hoặc thứ tự đúng" /></label>}</section>}</main>}
  </section>;
}

function UploadCard({ icon, title, note, file, accept, onFile }: { icon: string; title: string; note: string; file?: File; accept: string; onFile: (file?: File) => void }) { return <label><input type="file" accept={accept} onChange={(e) => onFile(e.target.files?.[0])} /><span>{icon}</span><div><b>{title}</b><small>{file ? file.name : note}</small></div><em>{file ? "Đổi tệp" : "Chọn tệp"}</em></label>; }

function WebDeck({ deck, onExit }: { deck: Deck; onExit: () => void }) {
  const [current, setCurrent] = useState(0); const [reveal, setReveal] = useState(false);
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement | null;
      if (event.key === " " && target?.tagName === "BUTTON") return;
      if (event.key === "ArrowRight" || event.key === " " || event.key === "PageDown") { event.preventDefault(); setReveal(false); setCurrent((value) => Math.min(deck.sections.length - 1, value + 1)); }
      else if (event.key === "ArrowLeft" || event.key === "PageUp") { event.preventDefault(); setReveal(false); setCurrent((value) => Math.max(0, value - 1)); }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [deck.sections.length]);
  const slide = deck.sections[current]; if (!slide) return null; return <section className="web-deck"><header><button onClick={onExit}>← Thoát trình chiếu</button><div><b>{deck.title}</b><small>{deck.subject} · Lớp {deck.grade}</small></div><span>{current + 1}/{deck.sections.length}</span><button onClick={() => document.documentElement.requestFullscreen?.()}>⛶ Toàn màn hình</button></header><main><small>{labels[slide.type]?.label.toUpperCase()}</small><h1>{slide.title}</h1><p>{slide.content}</p>{slide.type === "keywords" && <div className="keyword-cloud">{(slide.items || []).map((item) => <b key={item}>{item}</b>)}</div>}{slide.type === "mindmap" && <div className="mindmap"><b>{slide.title}</b><section>{(slide.items || []).map((item) => <span key={item}>{item}</span>)}</section></div>}{new Set(["multiple_choice", "true_false", "short_answer", "ordering", "matching"]).has(slide.type) && <div className={`deck-activity ${slide.type}`}>{(slide.items || []).map((item, index) => <button key={item}><span>{String.fromCharCode(65 + index)}</span>{item}</button>)}<button className="reveal" onClick={() => setReveal(!reveal)}>{reveal ? `Đáp án: ${slide.answer || "Giáo viên chưa thiết lập"}` : "Hiện đáp án"}</button></div>}</main><footer><button disabled={current === 0} onClick={() => { setReveal(false); setCurrent(current - 1); }}>← Trang trước</button><div>{deck.sections.map((_, i) => <i key={i} className={i === current ? "active" : ""} />)}</div><button disabled={current === deck.sections.length - 1} onClick={() => { setReveal(false); setCurrent(current + 1); }}>Trang tiếp →</button></footer></section>; }
