"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { InteractiveVideoEditor, InteractiveVideoPlayer, type InteractiveVideoConfig } from "./interactive-video";

type Notice = (message: string) => void;
type Progress = { currentSection: number; completedSections: string[]; answers: Record<string, string>; score: number | null; status: "in_progress" | "completed" };
type VideoLesson = {
  id?: string; teacherName?: string; title: string; subject: string; grade: string; className: string; summary: string;
  durationMinutes: number; deliveryMode: "home"; status: "draft" | "published" | "archived"; coverColor: string;
  objectives: string[]; sections: Array<{ id: string; type: "interactive_video"; title: string; content: string; deliveryMode: "home"; interactiveVideo: InteractiveVideoConfig }>;
  progress?: Progress | null; stats?: { learners: number; completed: number; averageScore: number | null };
};

const uid = () => `video-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
const blankLesson = (): VideoLesson => ({
  title: "", subject: "Toán", grade: "10", className: "10A1", summary: "", durationMinutes: 30, deliveryMode: "home", status: "draft", coverColor: "#155eef", objectives: [""],
  sections: [{ id: uid(), type: "interactive_video", title: "Video bài học", content: "", deliveryMode: "home", interactiveVideo: { sourceType: "video", voice: "nova", checkpoints: [] } }],
});
async function api<T>(url: string, options?: RequestInit) { const response = await fetch(url, options); const result = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(result.error || "Không thể xử lý bài học eLearning"); return result; }
function normalize(lesson: VideoLesson) { return { ...lesson, deliveryMode: lesson.deliveryMode || lesson.sections?.[0]?.deliveryMode || "home" } as VideoLesson; }
function configOf(lesson: VideoLesson) { return lesson.sections[0]?.interactiveVideo || { sourceType: "video", voice: "nova", checkpoints: [] }; }
function parsedResults(lesson: VideoLesson, answers: Record<string, string>) {
  return configOf(lesson).checkpoints.map((checkpoint) => { try { const value = JSON.parse(answers[checkpoint.id] || "{}") as { earned?: number; total?: number; correct?: boolean }; return { ...checkpoint, earned: Number(value.earned || 0), total: Number(value.total || checkpoint.points), correct: Boolean(value.correct), answered: Boolean(answers[checkpoint.id]) }; } catch { return { ...checkpoint, earned: 0, total: checkpoint.points, correct: false, answered: false }; } });
}
function scoreOf(lesson: VideoLesson, answers: Record<string, string>) { const rows = parsedResults(lesson, answers); const total = rows.reduce((sum, row) => sum + row.total, 0); const earned = rows.reduce((sum, row) => sum + row.earned, 0); return { earned, total, percent: total ? Math.round(earned * 100 / total) : 100, ten: total ? Math.round(earned * 100 / total) / 10 : 10 }; }

export function ELearningModule({ role, notify, myClassNames = [], allClassNames = [] }: { role: "teacher" | "student" | "admin"; notify: Notice; myClassNames?: string[]; allClassNames?: string[] }) {
  return role === "student" ? <StudentVideoLibrary notify={notify} myClassNames={myClassNames} allClassNames={allClassNames} /> : <TeacherVideoStudio notify={notify} />;
}

function TeacherVideoStudio({ notify }: { notify: Notice }) {
  const [lessons, setLessons] = useState<VideoLesson[]>([]); const [editor, setEditor] = useState<VideoLesson | null>(null); const [preview, setPreview] = useState<VideoLesson | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { const result = await api<{ lessons: VideoLesson[] }>("/api/elearning"); setLessons((result.lessons || []).map(normalize).filter((lesson) => lesson.deliveryMode === "home")); } catch (error) { notify(error instanceof Error ? error.message : "Không thể tải kho eLearning"); } finally { setLoading(false); } }, [notify]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  const act = async (action: "publish" | "unpublish" | "duplicate" | "delete", lesson: VideoLesson) => { if (!lesson.id) return; if (action === "delete" && !window.confirm(`Xóa bài “${lesson.title}”?`)) return; try { await api("/api/elearning", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, id: lesson.id }) }); notify(action === "publish" ? "Đã giao bài cho học sinh" : action === "unpublish" ? "Đã thu hồi bài học" : action === "duplicate" ? "Đã nhân bản bài học" : "Đã xóa bài học"); await load(); } catch (error) { notify(error instanceof Error ? error.message : "Không thể cập nhật bài học"); } };
  if (preview) return <VideoLearningPlayer lesson={preview} preview onExit={() => setPreview(null)} notify={notify} />;
  if (editor) return <VideoLessonBuilder lesson={editor} onChange={setEditor} onExit={() => setEditor(null)} onPreview={() => setPreview(editor)} onSaved={() => { setEditor(null); void load(); }} notify={notify} />;
  const published = lessons.filter((item) => item.status === "published").length;
  return <section className="video-studio">
    <div className="video-studio-hero"><div><small>E-LEARNING VIDEO TƯƠNG TÁC</small><h2>Tạo bài tự học theo mốc thời gian</h2><p>Một video, một tiến trình rõ ràng. Học sinh xem lần lượt, video tự dừng tại câu hỏi và chỉ tiếp tục sau khi đã trả lời.</p><button onClick={() => setEditor(blankLesson())}>＋ Tạo bài eLearning mới</button></div><div className="video-studio-stats"><article><b>{lessons.length}</b><span>Tổng bài</span></article><article><b>{published}</b><span>Đang giao</span></article><article><b>{lessons.reduce((sum, item) => sum + (item.stats?.learners || 0), 0)}</b><span>Lượt học</span></article></div></div>
    <div className="elearning-principles"><article><span>1</span><div><b>Tải video hoặc slide</b><small>MP4, WebM, MOV, PowerPoint, PDF</small></div></article><article><span>2</span><div><b>Gắn câu hỏi phút–giây</b><small>Video tự dừng đúng thời điểm</small></div></article><article><span>3</span><div><b>Khóa tua và bắt buộc trả lời</b><small>Không bỏ qua nội dung hay câu hỏi</small></div></article><article><span>4</span><div><b>Tự chấm và lưu tiến độ</b><small>Xem điểm từng mốc và toàn bài</small></div></article></div>
    <div className="learning-section-head"><div><b>Kho video bài học</b><small>Quản lý bài nháp, bài đã giao và kết quả học sinh</small></div><button onClick={() => setEditor(blankLesson())}>＋ Tạo video bài học</button></div>
    {loading ? <div className="learning-empty">Đang tải kho eLearning...</div> : lessons.length === 0 ? <div className="learning-empty"><span>▶</span><b>Chưa có video bài học</b><p>Hãy tạo bài đầu tiên theo quy trình bốn bước.</p></div> : <div className="video-lesson-grid">{lessons.map((lesson) => { const config = configOf(lesson); return <article key={lesson.id}><div className="video-card-cover"><span>▶</span><small>{lesson.subject} · Lớp {lesson.grade}</small><i>{lesson.status === "published" ? "Đang giao" : "Bản nháp"}</i></div><section><h3>{lesson.title}</h3><p>{lesson.summary || "Video tự học có câu hỏi tương tác."}</p><div className="video-card-meta"><span>◷ {lesson.durationMinutes} phút</span><span>◆ {config.checkpoints.length} mốc câu hỏi</span><span>🔒 Khóa tua</span></div><div className="video-card-results"><span><b>{lesson.stats?.learners || 0}</b> học sinh</span><span><b>{lesson.stats?.completed || 0}</b> hoàn thành</span></div><footer><button onClick={() => setEditor(lesson)}>Chỉnh sửa</button><button onClick={() => setPreview(lesson)}>Xem thử</button>{lesson.status === "published" ? <button onClick={() => void act("unpublish", lesson)}>Thu hồi</button> : <button className="publish" onClick={() => void act("publish", lesson)}>Giao bài</button>}<div><button>•••</button><span><button onClick={() => void act("duplicate", lesson)}>Nhân bản</button><button onClick={() => void act("delete", lesson)}>Xóa</button></span></div></footer></section></article>; })}</div>}
  </section>;
}

function VideoLessonBuilder({ lesson, onChange, onExit, onPreview, onSaved, notify }: { lesson: VideoLesson; onChange: (lesson: VideoLesson) => void; onExit: () => void; onPreview: () => void; onSaved: () => void; notify: Notice }) {
  const [step, setStep] = useState(1); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const config = configOf(lesson); const setLesson = (changes: Partial<VideoLesson>) => onChange({ ...lesson, ...changes });
  const setConfig = (interactiveVideo: InteractiveVideoConfig) => setLesson({ sections: [{ ...lesson.sections[0], interactiveVideo }] });
  const validateStep = (target: number) => { if (target > 1 && (!lesson.title.trim() || !lesson.subject.trim())) return notify("Vui lòng nhập tên bài học và môn học"); if (target > 2 && !config.videoUrl && !config.slideFileName) return notify("Vui lòng tải video hoặc slide bài giảng"); setStep(target); };
  const save = async (publish = false) => { if (!lesson.title.trim() || !lesson.subject.trim()) return notify("Vui lòng nhập tên và môn học"); if (!config.videoUrl && !config.slideFileName) return notify("Bài học cần có video hoặc slide nguồn"); if (!config.checkpoints.length) return notify("Hãy tạo ít nhất một mốc câu hỏi"); setSaving(true); try { const saved = await api<{ lesson: VideoLesson }>("/api/elearning", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "save", id: lesson.id, lesson: { ...lesson, deliveryMode: "home", sections: [{ ...lesson.sections[0], deliveryMode: "home" }] } }) }); if (publish && saved.lesson.id) await api("/api/elearning", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "publish", id: saved.lesson.id }) }); notify(publish ? "Đã giao video bài học cho học sinh" : "Đã lưu bản nháp eLearning"); onSaved(); } catch (error) { notify(error instanceof Error ? error.message : "Không thể lưu bài học"); } finally { setSaving(false); } };
  return <section className="video-builder"><header><button onClick={onExit}>← Kho eLearning</button><div><b>{lesson.id ? "Chỉnh sửa video bài học" : "Tạo eLearning video mới"}</b><small>Bài tự học ở nhà · khóa tua · tự chấm</small></div><nav><button onClick={onPreview}>▷ Xem thử</button><button disabled={saving} onClick={() => void save(false)}>Lưu nháp</button><button className="publish" disabled={saving} onClick={() => void save(true)}>Giao cho lớp</button></nav></header>
    <div className="video-builder-steps">{[[1,"Thông tin bài học"],[2,"Video hoặc slide"],[3,"Mốc câu hỏi"],[4,"Kiểm tra & giao bài"]].map(([number, label]) => <button key={number} className={step === number ? "active" : step > Number(number) ? "done" : ""} onClick={() => validateStep(Number(number))}><span>{step > Number(number) ? "✓" : number}</span><b>{label}</b></button>)}</div>
    {step === 1 && <main className="video-info-step"><div><small>BƯỚC 1/4</small><h2>Thông tin video bài học</h2><p>Thông tin này giúp học sinh nhận biết bài, lớp học và mục tiêu cần hoàn thành.</p></div><section><div className="video-info-fields"><label className="wide">Tên bài học<input value={lesson.title} onChange={(e) => setLesson({ title: e.target.value })} placeholder="Ví dụ: Hàm số bậc hai và đồ thị" /></label><label>Môn học<input value={lesson.subject} onChange={(e) => setLesson({ subject: e.target.value })} /></label><label>Khối<select value={lesson.grade} onChange={(e) => setLesson({ grade: e.target.value })}><option>10</option><option>11</option><option>12</option></select></label><label>Lớp được giao<input value={lesson.className} onChange={(e) => setLesson({ className: e.target.value })} /></label><label>Thời lượng dự kiến<input type="number" min="5" max="240" value={lesson.durationMinutes} onChange={(e) => setLesson({ durationMinutes: Number(e.target.value) })} /></label><label className="wide">Mô tả bài học<textarea value={lesson.summary} onChange={(e) => setLesson({ summary: e.target.value })} placeholder="Nêu ngắn gọn nội dung học sinh sẽ học..." /></label><label className="wide">Mục tiêu cần đạt<textarea value={lesson.objectives.join("\n")} onChange={(e) => setLesson({ objectives: e.target.value.split("\n") })} placeholder="Mỗi mục tiêu trên một dòng" /></label></div><button className="builder-next" onClick={() => validateStep(2)}>Tiếp tục chọn video →</button></section></main>}
    {step === 2 && <main className="video-source-step"><div><small>BƯỚC 2/4</small><h2>Chọn nguồn tạo video bài học</h2><p>Tải video có sẵn hoặc dùng PowerPoint/PDF để AI tạo kịch bản và giọng đọc bài giảng.</p></div><section><InteractiveVideoEditor value={config} onChange={setConfig} context={`${lesson.title}\n${lesson.subject} lớp ${lesson.grade}\n${lesson.summary}\n${lesson.objectives.join("\n")}`} notify={(value) => { setMessage(value); notify(value); }} focus="source" />{message && <div className="studio-message">{message}</div>}<button className="builder-next" onClick={() => validateStep(3)}>Tiếp tục đặt mốc câu hỏi →</button></section></main>}
    {step === 3 && <main className="checkpoint-builder-step"><div className="checkpoint-step-head"><div><small>BƯỚC 3/4</small><h2>Đặt câu hỏi tại từng mốc phút–giây</h2><p>Video tự dừng tại mỗi mốc. Học sinh phải nộp câu trả lời trước khi được xem tiếp.</p></div><div><b>{config.checkpoints.length}</b><span>mốc đã tạo</span></div></div><InteractiveVideoEditor value={config} onChange={setConfig} context={lesson.title} notify={notify} focus="checkpoints" /><button className="builder-next" onClick={() => validateStep(4)}>Kiểm tra bài học →</button></main>}
    {step === 4 && <main className="video-review-step"><div className="review-summary"><small>BƯỚC 4/4</small><h2>Sẵn sàng giao bài</h2><div><article><span>▶</span><b>{config.videoFileName || config.slideFileName || "Video bài học"}</b><small>{config.sourceType === "slides" ? "Tạo lời giảng AI từ slide" : "Video đã tải lên"}</small></article><article><span>◆</span><b>{config.checkpoints.length} mốc câu hỏi</b><small>Bắt buộc trả lời để tiếp tục</small></article><article><span>🔒</span><b>Đã khóa tua video</b><small>Học theo đúng trình tự</small></article><article><span>✓</span><b>Tự chấm và lưu điểm</b><small>Kết quả theo từng câu hỏi</small></article></div><footer><button onClick={onPreview}>▷ Xem thử như học sinh</button><button onClick={() => void save(false)} disabled={saving}>Lưu nháp</button><button className="publish" onClick={() => void save(true)} disabled={saving}>Giao bài cho {lesson.className}</button></footer></div></main>}
  </section>;
}

function StudentVideoLibrary({ notify, myClassNames, allClassNames }: { notify: Notice; myClassNames: string[]; allClassNames: string[] }) {
  const [lessons, setLessons] = useState<VideoLesson[]>([]); const [selected, setSelected] = useState<VideoLesson | null>(null); const [loading, setLoading] = useState(true);
  // Chỉ ẩn bài khi lớp được giao trùng với một lớp có thật mà em không tham gia;
  // bài giao cho lớp không có trong danh sách (dữ liệu cũ, giao chung) vẫn hiển thị.
  const visibleToMe = useCallback((lesson: VideoLesson) => {
    const assigned = (lesson.className || "").trim();
    if (!assigned || !allClassNames.includes(assigned)) return true;
    return myClassNames.includes(assigned);
  }, [myClassNames, allClassNames]);
  const load = useCallback(async () => { try { const result = await api<{ lessons: VideoLesson[] }>("/api/elearning"); setLessons((result.lessons || []).map(normalize).filter((lesson) => lesson.deliveryMode === "home").filter(visibleToMe)); } catch (error) { notify(error instanceof Error ? error.message : "Không thể tải bài học"); } finally { setLoading(false); } }, [notify, visibleToMe]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  const open = async (lesson: VideoLesson) => { try { const result = await api<{ lesson: VideoLesson }>(`/api/elearning?id=${encodeURIComponent(lesson.id || "")}`); setSelected(normalize(result.lesson)); } catch (error) { notify(error instanceof Error ? error.message : "Không thể mở bài học"); } };
  if (selected) return <VideoLearningPlayer lesson={selected} onExit={() => { setSelected(null); void load(); }} notify={notify} />;
  return <section className="student-video-library"><div className="student-video-hero"><div><small>PHÒNG TỰ HỌC VIDEO</small><h2>Xem bài giảng, trả lời và tiến bộ</h2><p>Video sẽ tự dừng tại các mốc kiểm tra. Em cần trả lời để tiếp tục và hệ thống sẽ lưu kết quả ngay.</p></div><div><b>{lessons.length}</b><span>Bài được giao</span></div></div><div className="student-video-rules"><span>🔒 Không tua video</span><span>◆ Trả lời theo mốc</span><span>✓ Chấm điểm tự động</span><span>↻ Tự lưu tiến độ</span></div>{loading ? <div className="learning-empty">Đang tải bài học...</div> : lessons.length === 0 ? <div className="learning-empty"><span>▶</span><b>Chưa có video được giao</b><p>Bài học sẽ xuất hiện khi giáo viên giao cho lớp.</p></div> : <div className="student-video-grid">{lessons.map((lesson) => { const answers = lesson.progress?.answers || {}; const results = parsedResults(lesson, answers); const answered = results.filter((row) => row.answered).length; const total = Math.max(1, results.length); const percent = lesson.progress?.status === "completed" ? 100 : Math.round(answered * 100 / total); const score = scoreOf(lesson, answers); return <article key={lesson.id}><div><span>{lesson.subject}</span><b>▶</b><small>{configOf(lesson).checkpoints.length} câu hỏi</small></div><section><small>GIÁO VIÊN {lesson.teacherName || "EDUPLAN"}</small><h3>{lesson.title}</h3><p>{lesson.summary}</p><div className="student-video-progress"><span><b>{percent}%</b> tiến độ</span><i><em style={{ width: `${percent}%` }} /></i></div>{answered > 0 && <div className="student-score-row"><span>Đã trả lời {answered}/{results.length}</span><b>{score.ten}/10 điểm</b></div>}<button onClick={() => void open(lesson)}>{lesson.progress?.status === "completed" ? "Xem lại kết quả" : answered ? "Tiếp tục học" : "Bắt đầu học"} →</button></section></article>; })}</div>}</section>;
}

function VideoLearningPlayer({ lesson, preview, onExit, notify }: { lesson: VideoLesson; preview?: boolean; onExit: () => void; notify: Notice }) {
  const [answers, setAnswers] = useState<Record<string, string>>(lesson.progress?.answers || {}); const [finished, setFinished] = useState(lesson.progress?.status === "completed"); const [saving, setSaving] = useState(false); const config = configOf(lesson);
  const rows = useMemo(() => parsedResults(lesson, answers), [lesson, answers]); const answered = rows.filter((row) => row.answered).length; const required = rows.filter((row) => row.required); const canFinish = required.every((row) => row.answered); const score = scoreOf(lesson, answers);
  const persist = async (nextAnswers: Record<string, string>, finish = false) => { if (preview || !lesson.id) return; setSaving(true); try { await api("/api/elearning", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "save_progress", id: lesson.id, currentSection: 0, completedSections: finish ? [lesson.sections[0].id] : [], answers: nextAnswers, finish }) }); if (finish) { setFinished(true); notify(`Đã hoàn thành bài học · ${score.ten}/10 điểm`); } } catch (error) { notify(error instanceof Error ? error.message : "Không thể lưu tiến độ"); } finally { setSaving(false); } };
  const answer = (id: string, value: string) => { const next = { ...answers, [id]: value }; setAnswers(next); void persist(next); };
  if (finished && !preview) return <section className="video-result-page"><header><button onClick={onExit}>← Phòng học</button><div><b>{lesson.title}</b><small>Kết quả bài học video</small></div></header><main><div className="result-score"><small>ĐIỂM BÀI HỌC</small><b>{score.ten}<span>/10</span></b><i>{score.percent >= 80 ? "Hoàn thành tốt" : score.percent >= 50 ? "Đã hoàn thành" : "Cần ôn tập thêm"}</i><p>Đã trả lời {answered}/{rows.length} câu hỏi tương tác</p></div><section><h2>Chi tiết từng mốc</h2>{rows.map((row, index) => <article key={row.id}><span>{index + 1}</span><div><b>{row.title || row.prompt}</b><small>Phút {Math.floor(row.timeSeconds / 60).toString().padStart(2, "0")}:{Math.floor(row.timeSeconds % 60).toString().padStart(2, "0")} · {row.answered ? "Đã trả lời" : "Chưa trả lời"}</small></div><strong>{row.earned}/{row.total} điểm</strong><i className={row.correct ? "correct" : "partial"}>{row.correct ? "✓" : "◎"}</i></article>)}</section></main><footer><button onClick={() => setFinished(false)}>▶ Xem lại video</button><button onClick={onExit}>Về danh sách bài học</button></footer></section>;
  return <section className="focused-video-player"><header><button onClick={onExit}>← Thoát bài học</button><div><b>{lesson.title}</b><small>{lesson.subject} · Lớp {lesson.grade}{preview ? " · Xem thử của giáo viên" : ""}</small></div><div><span>{answered}/{rows.length} câu</span><i><em style={{ width: `${rows.length ? answered * 100 / rows.length : 0}%` }} /></i></div></header><main><section><InteractiveVideoPlayer config={config} answers={answers} onAnswer={answer} notify={notify} /></section><aside><small>TIẾN ĐỘ BÀI HỌC</small><h3>{lesson.title}</h3><div className="player-rule"><span>🔒</span><p><b>Video khóa tua</b><small>Xem theo đúng trình tự</small></p></div><nav>{rows.map((row, index) => <article key={row.id} className={row.answered ? "done" : ""}><span>{row.answered ? "✓" : index + 1}</span><div><b>{row.title || `Câu hỏi ${index + 1}`}</b><small>{Math.floor(row.timeSeconds / 60).toString().padStart(2, "0")}:{Math.floor(row.timeSeconds % 60).toString().padStart(2, "0")} · {row.points} điểm</small></div></article>)}</nav><div className="live-score"><span>Điểm hiện tại</span><b>{score.ten}/10</b></div><button disabled={!canFinish || saving} onClick={() => void persist(answers, true)}>{saving ? "Đang lưu..." : canFinish ? "Hoàn thành và xem điểm" : `Còn ${required.filter((row) => !row.answered).length} câu bắt buộc`}</button></aside></main></section>;
}
