import { getRequestAccount } from "../../auth";

type Stored = { body: ReadableStream; httpMetadata?: { contentType?: string }; customMetadata?: Record<string, string> };
type Bucket = { put: (key: string, value: ReadableStream, options?: { httpMetadata?: { contentType?: string; contentDisposition?: string }; customMetadata?: Record<string, string> }) => Promise<unknown>; get: (key: string) => Promise<Stored | null> };
const allowed = new Set(["mp4", "webm", "mov", "ppt", "pptx", "pdf"]); const max = 100 * 1024 * 1024;
async function storage() { const { env } = await import("cloudflare:workers"); const bucket = (env as unknown as { BUCKET?: Bucket }).BUCKET; if (!bucket) throw new Error("Kho học liệu chưa được cấu hình"); return bucket; }
async function account(request: Request, upload = false) { const identity = await getRequestAccount(request); if (!identity?.account) throw new Error("Cần đăng nhập"); if (upload && !new Set(["teacher", "admin"]).has(identity.account.role)) throw new Error("Chỉ giáo viên được tải học liệu eLearning"); return identity.account; }
function name(value: string) { return value.replace(/[\r\n"\\]/g, "_").slice(0, 180); }
function fail(error: unknown) { const message = error instanceof Error ? error.message : "Không thể xử lý học liệu"; return Response.json({ error: message }, { status: message === "Cần đăng nhập" ? 401 : message.startsWith("Chỉ ") ? 403 : 400 }); }
export async function POST(request: Request) { try { const owner = await account(request, true); const form = await request.formData(); const file = form.get("file"); if (!(file instanceof File)) return Response.json({ error: "Chưa chọn tệp" }, { status: 400 }); if (file.size <= 0 || file.size > max) return Response.json({ error: "Tệp phải nhỏ hơn 100 MB" }, { status: 413 }); const ext = file.name.split(".").pop()?.toLowerCase() || ""; if (!allowed.has(ext)) return Response.json({ error: "Chỉ nhận MP4, WebM, MOV, PowerPoint hoặc PDF" }, { status: 415 }); const key = `learning/${crypto.randomUUID()}.${ext}`; await (await storage()).put(key, file.stream(), { httpMetadata: { contentType: file.type || "application/octet-stream", contentDisposition: `inline; filename="${name(file.name)}"` }, customMetadata: { owner: owner.accountKey, originalName: name(file.name) } }); return Response.json({ file: { id: key, name: name(file.name), size: file.size, url: `/api/learning-files?id=${encodeURIComponent(key)}` } }); } catch (e) { return fail(e); } }
export async function GET(request: Request) { try { await account(request); const key = new URL(request.url).searchParams.get("id") || ""; if (!/^learning\/[0-9a-f-]{36}\.[a-z0-9]{2,5}$/.test(key)) return Response.json({ error: "Mã học liệu không hợp lệ" }, { status: 400 }); const object = await (await storage()).get(key); if (!object) return Response.json({ error: "Không tìm thấy học liệu" }, { status: 404 }); return new Response(object.body, { headers: { "Content-Type": object.httpMetadata?.contentType || "application/octet-stream", "Content-Disposition": `inline; filename="${name(object.customMetadata?.originalName || "hoc-lieu")}"`, "Cache-Control": "private, max-age=300", "X-Content-Type-Options": "nosniff" } }); } catch (e) { return fail(e); } }
