create table if not exists eduplan_private.classes (
  id bigint generated by default as identity primary key,
  code citext not null unique,
  name text not null,
  grade text not null check (grade in ('10', '11', '12')),
  homeroom_teacher_id uuid references eduplan_private.accounts(id) on delete set null,
  created_by uuid references eduplan_private.accounts(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists eduplan_private.class_students (
  student_id uuid primary key references eduplan_private.accounts(id) on delete cascade,
  class_id bigint not null references eduplan_private.classes(id) on delete cascade,
  assigned_by uuid references eduplan_private.accounts(id) on delete set null,
  assigned_at timestamptz not null default now()
);

create table if not exists eduplan_private.class_subject_teachers (
  class_id bigint not null references eduplan_private.classes(id) on delete cascade,
  subject text not null,
  teacher_id uuid not null references eduplan_private.accounts(id) on delete cascade,
  assigned_by uuid references eduplan_private.accounts(id) on delete set null,
  assigned_at timestamptz not null default now(),
  primary key (class_id, subject)
);

create index if not exists classes_homeroom_teacher_idx on eduplan_private.classes(homeroom_teacher_id);
create index if not exists class_students_class_idx on eduplan_private.class_students(class_id);
create index if not exists class_subject_teachers_teacher_idx on eduplan_private.class_subject_teachers(teacher_id);
alter table eduplan_private.classes enable row level security;
alter table eduplan_private.class_students enable row level security;
alter table eduplan_private.class_subject_teachers enable row level security;
revoke all on eduplan_private.classes, eduplan_private.class_students, eduplan_private.class_subject_teachers from public, anon, authenticated;

create or replace function public.eduplan_bulk_classes(p_secret text, p_token text, p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor eduplan_private.accounts;
  v_teacher eduplan_private.accounts;
  v_student eduplan_private.accounts;
  v_class eduplan_private.classes;
  v_item record;
  v_row jsonb;
  v_classes jsonb := coalesce(p_payload->'classes', '[]'::jsonb);
  v_students jsonb := coalesce(p_payload->'students', '[]'::jsonb);
  v_subject_teachers jsonb := coalesce(p_payload->'subjectTeachers', '[]'::jsonb);
  v_errors jsonb := '[]'::jsonb;
  v_codes text[] := '{}'::text[];
  v_seen_students text[] := '{}'::text[];
  v_seen_subjects text[] := '{}'::text[];
  v_allowed_subjects text[] := array[
    'Toán','Ngữ văn','Tiếng Anh','Ngoại ngữ khác','Vật lí','Hóa học','Sinh học','Lịch sử','Địa lí',
    'Giáo dục kinh tế và pháp luật','Tin học','Công nghệ','Giáo dục thể chất','Giáo dục quốc phòng và an ninh',
    'Âm nhạc','Mĩ thuật','Hoạt động trải nghiệm, hướng nghiệp','Nội dung giáo dục của địa phương'
  ];
  v_row_number integer;
  v_code text;
  v_name text;
  v_grade text;
  v_username text;
  v_student_code text;
  v_subject text;
  v_key text;
  v_exists boolean;
  v_created integer := 0;
  v_updated integer := 0;
  v_assigned_students integer := 0;
  v_assigned_subjects integer := 0;
  v_workspace_classes jsonb := '[]'::jsonb;
  v_imported_classes jsonb := '[]'::jsonb;
begin
  if not eduplan_private.valid_app_secret(p_secret) then raise exception 'Khóa máy chủ không hợp lệ'; end if;
  if jsonb_typeof(v_classes) <> 'array' or jsonb_typeof(v_students) <> 'array' or jsonb_typeof(v_subject_teachers) <> 'array' then
    raise exception 'Dữ liệu lớp học không hợp lệ';
  end if;
  if jsonb_array_length(v_classes) = 0 then raise exception 'Trang Lớp học chưa có dữ liệu'; end if;
  if jsonb_array_length(v_classes) > 300 or jsonb_array_length(v_students) > 3000 or jsonb_array_length(v_subject_teachers) > 3000 then
    raise exception 'Tệp vượt giới hạn nhập dữ liệu';
  end if;

  select a.* into v_actor
  from eduplan_private.sessions s join eduplan_private.accounts a on a.id = s.account_id
  where s.token_hash = encode(extensions.digest(coalesce(p_token, ''), 'sha256'), 'hex') and s.expires_at > now()
  limit 1;
  if v_actor.id is null then raise exception 'Cần đăng nhập'; end if;
  if v_actor.role <> 'admin' or v_actor.status <> 'active' then raise exception 'Chỉ quản trị viên được phép thực hiện'; end if;

  for v_item in select value, ordinality from jsonb_array_elements(v_classes) with ordinality as rows(value, ordinality)
  loop
    v_row := v_item.value;
    v_row_number := coalesce(nullif(v_row->>'rowNumber', '')::integer, v_item.ordinality::integer + 4);
    v_code := upper(trim(coalesce(v_row->>'code', '')));
    v_name := trim(coalesce(v_row->>'name', ''));
    v_grade := trim(coalesce(v_row->>'grade', ''));
    v_username := lower(trim(coalesce(v_row->>'homeroomUsername', '')));
    if v_code !~ '^[A-Z0-9._-]{2,30}$' then
      v_errors := v_errors || jsonb_build_array(jsonb_build_object('sheet','Lớp học','rowNumber',v_row_number,'message','Mã lớp chỉ gồm chữ, số, dấu chấm, gạch ngang hoặc gạch dưới'));
    elsif v_code = any(v_codes) then
      v_errors := v_errors || jsonb_build_array(jsonb_build_object('sheet','Lớp học','rowNumber',v_row_number,'message','Mã lớp bị lặp trong tệp'));
    elsif v_name = '' then
      v_errors := v_errors || jsonb_build_array(jsonb_build_object('sheet','Lớp học','rowNumber',v_row_number,'message','Thiếu tên lớp'));
    elsif v_grade not in ('10','11','12') then
      v_errors := v_errors || jsonb_build_array(jsonb_build_object('sheet','Lớp học','rowNumber',v_row_number,'message','Khối lớp phải là 10, 11 hoặc 12'));
    else
      select a.* into v_teacher from eduplan_private.accounts a where a.username = v_username and a.role = 'teacher' and a.status = 'active' limit 1;
      if v_teacher.id is null then
        v_errors := v_errors || jsonb_build_array(jsonb_build_object('sheet','Lớp học','rowNumber',v_row_number,'message','Không tìm thấy tài khoản GVCN đang hoạt động: ' || v_username));
      end if;
      v_codes := array_append(v_codes, v_code);
    end if;
  end loop;

  for v_item in select value, ordinality from jsonb_array_elements(v_students) with ordinality as rows(value, ordinality)
  loop
    v_row := v_item.value;
    v_row_number := coalesce(nullif(v_row->>'rowNumber', '')::integer, v_item.ordinality::integer + 4);
    v_code := upper(trim(coalesce(v_row->>'classCode', '')));
    v_student_code := trim(coalesce(v_row->>'studentCode', ''));
    if not (v_code = any(v_codes)) then
      v_errors := v_errors || jsonb_build_array(jsonb_build_object('sheet','Học sinh vào lớp','rowNumber',v_row_number,'message','Mã lớp không có trong trang Lớp học: ' || v_code));
    elsif v_student_code = '' then
      v_errors := v_errors || jsonb_build_array(jsonb_build_object('sheet','Học sinh vào lớp','rowNumber',v_row_number,'message','Thiếu mã học sinh'));
    elsif lower(v_student_code) = any(v_seen_students) then
      v_errors := v_errors || jsonb_build_array(jsonb_build_object('sheet','Học sinh vào lớp','rowNumber',v_row_number,'message','Học sinh bị gán lặp trong tệp'));
    else
      select a.* into v_student from eduplan_private.accounts a
      where a.role = 'student' and a.status = 'active' and (a.student_code = v_student_code or a.username = lower(v_student_code)) limit 1;
      if v_student.id is null then
        v_errors := v_errors || jsonb_build_array(jsonb_build_object('sheet','Học sinh vào lớp','rowNumber',v_row_number,'message','Không tìm thấy mã hoặc tài khoản học sinh: ' || v_student_code));
      end if;
      v_seen_students := array_append(v_seen_students, lower(v_student_code));
    end if;
  end loop;

  for v_item in select value, ordinality from jsonb_array_elements(v_subject_teachers) with ordinality as rows(value, ordinality)
  loop
    v_row := v_item.value;
    v_row_number := coalesce(nullif(v_row->>'rowNumber', '')::integer, v_item.ordinality::integer + 4);
    v_code := upper(trim(coalesce(v_row->>'classCode', '')));
    v_subject := trim(coalesce(v_row->>'subject', ''));
    v_username := lower(trim(coalesce(v_row->>'teacherUsername', '')));
    v_key := lower(v_code || '|' || v_subject);
    if not (v_code = any(v_codes)) then
      v_errors := v_errors || jsonb_build_array(jsonb_build_object('sheet','Phân công GVBM','rowNumber',v_row_number,'message','Mã lớp không có trong trang Lớp học: ' || v_code));
    elsif not (v_subject = any(v_allowed_subjects)) then
      v_errors := v_errors || jsonb_build_array(jsonb_build_object('sheet','Phân công GVBM','rowNumber',v_row_number,'message','Môn học không nằm trong danh mục EduPlan AI'));
    elsif v_key = any(v_seen_subjects) then
      v_errors := v_errors || jsonb_build_array(jsonb_build_object('sheet','Phân công GVBM','rowNumber',v_row_number,'message','Môn học bị phân công lặp trong cùng lớp'));
    else
      select a.* into v_teacher from eduplan_private.accounts a where a.username = v_username and a.role = 'teacher' and a.status = 'active' limit 1;
      if v_teacher.id is null then
        v_errors := v_errors || jsonb_build_array(jsonb_build_object('sheet','Phân công GVBM','rowNumber',v_row_number,'message','Không tìm thấy tài khoản GVBM đang hoạt động: ' || v_username));
      end if;
      v_seen_subjects := array_append(v_seen_subjects, v_key);
    end if;
  end loop;

  if jsonb_array_length(v_errors) > 0 then
    return jsonb_build_object('createdClasses',0,'updatedClasses',0,'assignedStudents',0,'assignedSubjects',0,'errors',v_errors);
  end if;

  for v_item in select value from jsonb_array_elements(v_classes) as rows(value)
  loop
    v_row := v_item.value;
    v_code := upper(trim(v_row->>'code'));
    v_name := trim(v_row->>'name');
    v_grade := trim(v_row->>'grade');
    v_username := lower(trim(v_row->>'homeroomUsername'));
    select exists(select 1 from eduplan_private.classes where code = v_code) into v_exists;
    select a.* into v_teacher from eduplan_private.accounts a where a.username = v_username and a.role = 'teacher' and a.status = 'active' limit 1;
    insert into eduplan_private.classes(code,name,grade,homeroom_teacher_id,created_by)
    values(v_code,v_name,v_grade,v_teacher.id,v_actor.id)
    on conflict(code) do update set name=excluded.name, grade=excluded.grade, homeroom_teacher_id=excluded.homeroom_teacher_id, updated_at=now()
    returning * into v_class;
    if v_exists then v_updated := v_updated + 1; else v_created := v_created + 1; end if;
  end loop;

  for v_item in select value from jsonb_array_elements(v_students) as rows(value)
  loop
    v_row := v_item.value;
    v_code := upper(trim(v_row->>'classCode'));
    v_student_code := trim(v_row->>'studentCode');
    select * into v_class from eduplan_private.classes where code = v_code;
    select a.* into v_student from eduplan_private.accounts a where a.role='student' and a.status='active' and (a.student_code=v_student_code or a.username=lower(v_student_code)) limit 1;
    insert into eduplan_private.class_students(student_id,class_id,assigned_by)
    values(v_student.id,v_class.id,v_actor.id)
    on conflict(student_id) do update set class_id=excluded.class_id, assigned_by=excluded.assigned_by, assigned_at=now();
    v_assigned_students := v_assigned_students + 1;
  end loop;

  for v_item in select value from jsonb_array_elements(v_subject_teachers) as rows(value)
  loop
    v_row := v_item.value;
    v_code := upper(trim(v_row->>'classCode'));
    v_subject := trim(v_row->>'subject');
    v_username := lower(trim(v_row->>'teacherUsername'));
    select * into v_class from eduplan_private.classes where code = v_code;
    select a.* into v_teacher from eduplan_private.accounts a where a.username=v_username and a.role='teacher' and a.status='active' limit 1;
    insert into eduplan_private.class_subject_teachers(class_id,subject,teacher_id,assigned_by)
    values(v_class.id,v_subject,v_teacher.id,v_actor.id)
    on conflict(class_id,subject) do update set teacher_id=excluded.teacher_id, assigned_by=excluded.assigned_by, assigned_at=now();
    v_assigned_subjects := v_assigned_subjects + 1;
  end loop;

  select coalesce(data->'classes','[]'::jsonb) into v_workspace_classes from eduplan_private.workspace_state where id='main';
  select coalesce(jsonb_agg(item),'[]'::jsonb) into v_workspace_classes
  from jsonb_array_elements(v_workspace_classes) item
  where not (upper(coalesce(item->>'code','')) = any(v_codes));

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', c.id, 'name', c.name, 'grade', c.grade, 'code', c.code::text,
    'subject', 'Lớp học khối ' || c.grade, 'students', (select count(*) from eduplan_private.class_students cs where cs.class_id=c.id),
    'progress', 0, 'ownerKey', ht.id::text, 'ownerName', ht.name,
    'homeroomTeacherKey', ht.id::text, 'homeroomTeacherName', ht.name, 'homeroomTeacherUsername', ht.username::text,
    'members', coalesce((select jsonb_agg(jsonb_build_object('key',s.id::text,'name',s.name,'joinedAt',cs.assigned_at) order by s.name)
      from eduplan_private.class_students cs join eduplan_private.accounts s on s.id=cs.student_id where cs.class_id=c.id),'[]'::jsonb),
    'subjectTeachers', coalesce((select jsonb_agg(jsonb_build_object('subject',cst.subject,'teacherKey',t.id::text,'teacherName',t.name,'teacherUsername',t.username::text) order by cst.subject)
      from eduplan_private.class_subject_teachers cst join eduplan_private.accounts t on t.id=cst.teacher_id where cst.class_id=c.id),'[]'::jsonb)
  ) order by c.grade,c.name),'[]'::jsonb) into v_imported_classes
  from eduplan_private.classes c join eduplan_private.accounts ht on ht.id=c.homeroom_teacher_id
  where upper(c.code::text) = any(v_codes);

  update eduplan_private.workspace_state set
    data=jsonb_set(coalesce(data,'{}'::jsonb),'{classes}',v_workspace_classes || v_imported_classes,true),
    updated_by=v_actor.id, updated_at=now()
  where id='main';

  return jsonb_build_object('createdClasses',v_created,'updatedClasses',v_updated,'assignedStudents',v_assigned_students,'assignedSubjects',v_assigned_subjects,'errors','[]'::jsonb);
end
$$;

revoke all on function public.eduplan_bulk_classes(text,text,jsonb) from public;
grant execute on function public.eduplan_bulk_classes(text,text,jsonb) to anon;
